import { test, expect } from '@playwright/test';

test('Test Add a new Developer', async ({ page }) => {
  await page.goto('http://localhost/mantisbt/login_page.php');
  await page.getByPlaceholder('Username').click();
  await page.getByPlaceholder('Username').fill('administrator');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByText('Only allow your session to be used from this IP address.').click();
  await page.getByPlaceholder('Password').click();
  await page.getByPlaceholder('Password').fill('PswA123456_');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Manage Users' }).click();
  await page.getByRole('link', { name: 'Create New Account' }).click();
  await page.locator('#user-username').click();
  await page.locator('#user-username').fill('developer2');
  await page.locator('#user-realname').click();
  await page.locator('#user-realname').fill('developer2 Name');
  await page.locator('#user-access-level').selectOption('55');
  await page.getByRole('button', { name: 'Create User' }).click();
  await page.getByRole('button', { name: 'Use Empty Password' }).click();
  await page.getByRole('link', { name: ' administrator ' }).click();
  await page.getByRole('link', { name: ' Logout' }).click();
  await page.getByPlaceholder('Username').click();
  await page.getByPlaceholder('Username').fill('developer2');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'developer2 ( developer2 Name )' }).click();
  await page.locator('#password').click();
  await page.locator('#password').fill('123456');
  await page.locator('#password-confirm').click();
  await page.locator('#password-confirm').fill('123456');
  await page.getByRole('button', { name: 'Update User' }).click();
  await page.getByPlaceholder('Username').click();
  await page.getByPlaceholder('Username').fill('developer2');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByPlaceholder('Password').click();
  await page.getByPlaceholder('Password').fill('123456');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'developer2 ( developer2 Name )' }).click();
  await page.getByRole('link', { name: ' developer2 ' }).click();
  await page.getByRole('link', { name: ' Logout' }).click();
});